# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160109_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='passWord',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
