# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_signup_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='passWord',
        ),
    ]
